"""Wi-Fi channel codecs: PDU envelope, message JSON, file records, heuristic, sealing.

Every byte string below is hand-computed from the recovered layouts, never
generated by the code under test. Evidence citations live in
emulator/plaudsim/wifi.py; this file checks the codecs against the layouts and
against known-answer vectors, and challenges the failure modes the phone-side
parsers exhibit.
"""

from __future__ import annotations

import sys
from datetime import timezone
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parents[1] / "emulator"))

from cryptography.exceptions import InvalidTag

from plaudsim.handshake import build_k3
from plaudsim.sealed import SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L, SealedSession
from plaudsim.wifi import (
    CIPHERTEXT_TYPE_THRESHOLD,
    DEVICE_TO_PHONE,
    MESSAGE_NAMES,
    MSG_FILE_SYNC_CONTENT,
    MSG_GET_FILE_LIST,
    MSG_HANDSHAKE,
    MSG_HEARTBEAT,
    PDU_HEADER_LEN,
    PHONE_TO_DEVICE,
    WS_PORT,
    FileListResponse,
    FileRecord,
    FileSyncContent,
    FileSyncStatus,
    GetFileListRequest,
    HandshakeRequest,
    HandshakeResponse,
    HeartbeatPing,
    HeartbeatPong,
    SayHello,
    SpeedTestResponse,
    UniversalError,
    WifiClose,
    WifiSealer,
    decode_for_device,
    decode_for_phone,
    file_name_for_session,
    looks_encrypted,
    pack_file_records,
    pack_pdu,
    pad_wifi_token,
    parse_file_records,
    parse_pdu,
)

# --- envelope ----------------------------------------------------------------


def test_heartbeat_pong_pdu_bytes_are_hand_computed():
    # {"stamp":1700000000} is 20 bytes; total 28 = 0x1c; type 3; jsonSize 0x14.
    wire = HeartbeatPong(1700000000).encode()
    assert wire == bytes.fromhex("1c000001" "0300" "1400") + b'{"stamp":1700000000}'
    pdu = parse_pdu(wire)
    assert (pdu.total_size, pdu.pdu_version, pdu.msg_type, pdu.json_size) == (28, 1, 3, 20)
    assert pdu.tail == b""
    assert pdu.json == {"stamp": 1700000000}


def test_handshake_request_pads_token_to_32_with_ascii_zero():
    wire = HandshakeRequest("abc", 7).encode()
    body = b'{"token":"abc' + b"0" * 29 + b'","stamp":7}'
    assert len(body) == 54
    assert wire == bytes.fromhex("3e000001" "0100" "3600") + body
    req = decode_for_device(wire)
    assert isinstance(req, HandshakeRequest)
    assert req.token == "abc" + "0" * 29 and req.stamp == 7


def test_pad_matches_k3_below_32_and_diverges_above():
    """padEnd never truncates; k3 does. Same rule up to 32 characters."""
    tok = "SYNTHETIC-TOKEN-0123456789ABCDEF"  # exactly 32
    assert pad_wifi_token(tok) == tok
    assert pad_wifi_token("x") == "x" + "0" * 31
    k3_token = build_k3("x", port_version=9)[6:].decode()
    assert k3_token == pad_wifi_token("x")
    longer = tok + "ZZ"
    assert pad_wifi_token(longer) == longer               # 34 chars, untouched
    assert build_k3(longer, port_version=9)[6:].decode() == tok  # k3 truncates


def test_pdu_with_tail_counts_the_tail_in_total_size():
    wire = FileSyncContent(session=5, offset=0, data=b"ab", last=True).encode()
    body = b'{"session":5,"offset":0,"length":2,"last":1}'
    assert len(body) == 44
    assert wire == bytes.fromhex("36000001" "0d00" "2c00") + body + b"ab"
    pdu = parse_pdu(wire, strict_total=True)
    assert pdu.tail == b"ab"


def test_parse_pdu_guards_mirror_the_sdk_messages():
    with pytest.raises(ValueError, match="Data too short for header"):
        parse_pdu(b"\x07\x00\x00\x01\x03\x00\x00")
    # header says 20 JSON bytes but only 3 follow
    with pytest.raises(ValueError, match="Data too short for JSON content"):
        parse_pdu(bytes.fromhex("0b000001" "0300" "1400") + b"{}x")
    # negative jsonSize (s16) is also "too short"
    with pytest.raises(ValueError, match="Data too short for JSON content"):
        parse_pdu(bytes.fromhex("08000001" "0300" "ffff"))
    # totalSize is not checked unless asked
    lying = bytes.fromhex("ff000001" "0300" "0200") + b"{}"
    assert parse_pdu(lying).total_size == 0xFF
    with pytest.raises(ValueError, match="totalSize"):
        parse_pdu(lying, strict_total=True)


def test_unparseable_json_yields_defaults_not_an_error():
    """BaseWifiResponse swallows JSONException; getters return their defaults."""
    wire = pack_pdu(MSG_HANDSHAKE, b"not json")
    pdu = parse_pdu(wire)
    assert pdu.json is None
    rsp = HandshakeResponse.from_pdu(pdu)
    assert rsp.status == -1 and rsp.session == ""


def test_type_mismatch_is_rejected_like_the_sdk():
    wire = HeartbeatPong(1).encode()
    with pytest.raises(ValueError, match="Type mismatch: expected 1, got 3"):
        HandshakeResponse.from_pdu(parse_pdu(wire))


def test_encoder_range_guards():
    with pytest.raises(ValueError):
        pack_pdu(0x8000, {})
    with pytest.raises(ValueError):
        pack_pdu(1, {}, pdu_version=256)
    with pytest.raises(ValueError):
        pack_pdu(1, b"x" * 0x8000)


def test_message_type_table_matches_the_ledger():
    expected = {
        0: "UniversalErr", 1: "Handshake", 2: "SayHello", 3: "Heartbeat", 4: "WifiClose", 5: "Tips",
        11: "GetFileList", 12: "FileSync", 13: "FileSyncContent", 14: "FileDelete", 15: "FileSyncStop",
        16: "ExtendExitTime", 20: "SendOTAFileInfo", 21: "RequestOTAPackage", 22: "OTAStatusSync",
        100: "SpeedTest", 101: "GetDeviceLog",
    }
    assert MESSAGE_NAMES == expected
    assert WS_PORT == 8081
    for t, cls in {**DEVICE_TO_PHONE, **PHONE_TO_DEVICE}.items():
        assert cls.TYPE == t


# --- the ciphertext heuristic ----------------------------------------------------


def _frame_with_type_word(word: int) -> bytes:
    return bytes.fromhex("08000001") + word.to_bytes(2, "little") + b"\x00\x00"


def test_heuristic_boundary_is_strictly_greater_than_200():
    assert CIPHERTEXT_TYPE_THRESHOLD == 200
    assert looks_encrypted(_frame_with_type_word(200)) is False
    assert looks_encrypted(_frame_with_type_word(201)) is True
    assert looks_encrypted(_frame_with_type_word(101)) is False       # highest real type
    assert looks_encrypted(_frame_with_type_word(0xFFFF)) is True
    assert looks_encrypted(_frame_with_type_word(0xFFFF)[:7]) is False  # "Message too short" path
    # a real plaintext PDU is never mistaken for ciphertext
    assert looks_encrypted(HeartbeatPong(1).encode()) is False


# --- file-list records ------------------------------------------------------------


def test_file_record_is_u32_u32_u16_little_endian():
    rec = FileRecord(0x12345678, 0x100, 2)
    assert rec.pack() == bytes.fromhex("78563412" "00010000" "0200")
    assert parse_file_records(rec.pack()) == [rec]


def test_file_list_response_bytes_and_partial_record_tolerance():
    rec = FileRecord(0x12345678, 0x100, 2)
    wire = FileListResponse(uid=0, status=0, count=1, offset=0, records=[rec]).encode()
    body = b'{"uid":0,"status":0,"count":1,"offset":0}'
    assert len(body) == 41
    assert wire == bytes.fromhex("3b000001" "0b00" "2900") + body + rec.pack()
    # the Kotlin loop is `while (i + 10 <= len)`: a dangling 4 bytes are ignored
    dangling = wire + b"\x01\x02\x03\x04"
    rsp = decode_for_phone(dangling)
    assert isinstance(rsp, FileListResponse) and rsp.records == [rec]
    assert parse_file_records(b"\x00" * 9) == []
    assert pack_file_records([]) == b""


def test_session_id_doubles_as_unix_timestamp_in_the_phone_file_name():
    assert file_name_for_session(1700000000, timezone.utc) == "2023-11-14_22-13-20.opus"
    assert file_name_for_session(99) == "log99"
    assert file_name_for_session(100, timezone.utc) == "1970-01-01_00-01-40.opus"


# --- per-message key semantics ----------------------------------------------------


def test_file_sync_content_tail_is_accepted_only_when_it_matches_length():
    good = FileSyncContent(1, 0, b"xyz", last=False).encode()
    assert decode_for_phone(good).data == b"xyz"
    # declared length 3 but 4 bytes follow -> getFileData returns empty
    bad = pack_pdu(MSG_FILE_SYNC_CONTENT, {"session": 1, "offset": 0, "length": 3, "last": 0}, b"wxyz")
    assert decode_for_phone(bad).data == b""
    # an empty last frame is a legitimate terminator
    fin = FileSyncContent(1, 10, b"", last=True).encode()
    parsed = decode_for_phone(fin)
    assert parsed.last is True and parsed.data == b"" and parsed.length == 0


def test_heartbeat_ping_emits_both_battery_spellings_and_int_charging():
    j = HeartbeatPing(87, True, 4100).to_json()
    assert j == {"battery": 87, "volume": 87, "charging": 1, "voltage": 4100}
    # a proto-path pen that only sent "volume" still parses
    only_volume = pack_pdu(MSG_HEARTBEAT, {"volume": 42, "charging": 0, "voltage": 1})
    ping = HeartbeatPing.from_pdu(parse_pdu(only_volume))
    assert ping.battery == 42 and ping.charging is False
    # a JSON boolean is NOT coerced by optInt: charging stays false
    boolean = pack_pdu(MSG_HEARTBEAT, {"battery": 1, "charging": True, "voltage": 1})
    assert HeartbeatPing.from_pdu(parse_pdu(boolean)).charging is False


def test_heartbeat_pong_accepts_the_empty_proto_form():
    assert HeartbeatPong.from_pdu(parse_pdu(pack_pdu(MSG_HEARTBEAT, {}))).stamp is None
    assert HeartbeatPong.from_pdu(parse_pdu(HeartbeatPong(9).encode())).stamp == 9


def test_get_file_list_single_is_serialised_as_int():
    assert GetFileListRequest(0, 0, False).to_json() == {"uid": 0, "start": 0, "single": 0}
    assert GetFileListRequest(7, 3, True).encode()[8:] == b'{"uid":7,"start":3,"single":1}'


def test_defaults_when_keys_are_absent_follow_the_optint_fallbacks():
    empty = {"status": None}
    assert FileSyncStatus.from_pdu(parse_pdu(pack_pdu(12, {}))) == FileSyncStatus(-1, 0, 0)
    assert UniversalError.from_pdu(parse_pdu(pack_pdu(0, {}))) == UniversalError(-1, "", 0, 0)
    assert WifiClose.from_pdu(parse_pdu(pack_pdu(4, {}))) == WifiClose("", 0)
    assert SayHello.from_pdu(parse_pdu(pack_pdu(2, {}))) == SayHello("", "", "", -1)
    del empty


def test_speed_test_tail_is_sized_from_total_size():
    wire = SpeedTestResponse(3, b"\x00" * 50).encode()
    assert SpeedTestResponse.from_pdu(parse_pdu(wire)).pack_data == b"\x00" * 50
    # a lying totalSize makes the proto f6 arraycopy fail; we surface it
    lying = bytearray(wire)
    lying[0] -= 1
    with pytest.raises(ValueError):
        SpeedTestResponse.from_pdu(parse_pdu(bytes(lying)))


def test_get_file_list_json_order_is_insertion_order():
    assert GetFileListRequest().encode()[8:] == b'{"uid":0,"start":0,"single":0}'
    assert MSG_GET_FILE_LIST == 11


# --- sealing ------------------------------------------------------------------------

# NIST GCM test case 14: AES-256 zero key, 96-bit zero IV, 16 zero plaintext bytes.
GCM14_CT = bytes.fromhex("cea7403d4d606b6e074ec5d3baf39d18")
GCM14_TAG = bytes.fromhex("d0d1c8a799996bf0265b98b5d48ab919")

# RFC 8439 section 2.8.2 AEAD_CHACHA20_POLY1305 vector (also used by test_r5_s7).
RFC_KEY = bytes.fromhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
RFC_NONCE = bytes.fromhex("070000004041424344454647")
RFC_AAD = bytes.fromhex("50515253c0c1c2c3c4c5c6c7")
RFC_PT = (
    b"Ladies and Gentlemen of the class of '99: If I could offer you "
    b"only one tip for the future, sunscreen would be it."
)
RFC_CT_TAG = bytes.fromhex(
    "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d6"
    "3dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b36"
    "92ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc"
    "3ff4def08e4b7a9de576d26586cec64b6116" "1ae10b594f09e26a7e902ecbd0600691"
)


def test_aes_gcm_wiring_against_the_nist_vector():
    sealer = WifiSealer(SealedSession(bytes(32), bytes(12), b""), use_aes=True)
    assert sealer.algorithm == "AES-GCM"
    assert sealer._seal_raw(bytes(16)) == GCM14_CT + GCM14_TAG
    assert sealer._open_raw(GCM14_CT + GCM14_TAG) == bytes(16)


def test_chacha_wiring_against_the_rfc_vector():
    sealer = WifiSealer(SealedSession(RFC_KEY, RFC_NONCE, RFC_AAD), use_aes=False)
    assert sealer.algorithm == "ChaCha20-Poly1305"
    assert sealer._seal_raw(RFC_PT) == RFC_CT_TAG


#: u16le at wire offset 4 of HeartbeatPong(1) sealed with the synthetic
#: (J, K, L) at seq 2 -- computed once with the `cryptography` primitives and
#: pinned, so a change to the sealing layout or the keys shows up here.
PONG_SEALED_U16_AT_4 = {False: 57069, True: 28869}   # ChaCha20-Poly1305, AES-GCM


@pytest.mark.parametrize("use_aes", [False, True])
def test_seal_frames_seq_then_pdu_and_opens_across_endpoints(use_aes):
    tx = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=use_aes)
    rx = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=use_aes)
    pdu = HeartbeatPong(1).encode()
    wire = tx.seal(pdu)
    assert tx.tx_seq == 2                       # SealedSession: reset 1, pre-increment
    assert len(wire) == 4 + len(pdu) + 16       # [u32 seq][pdu] + 16-byte tag
    # Review T11: the classifier outcome is deterministic for fixed keys and
    # seq. Recompute the ciphertext with the AEAD primitive directly (not via
    # WifiSealer) and pin both the bytes 4..5 and the verdict.
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305

    aead = AESGCM(SYNTHETIC_J) if use_aes else ChaCha20Poly1305(SYNTHETIC_J)
    expected = aead.encrypt(SYNTHETIC_K, (2).to_bytes(4, "little") + pdu, SYNTHETIC_L)
    assert wire == expected
    u16_at_4 = wire[4] | wire[5] << 8
    assert u16_at_4 == PONG_SEALED_U16_AT_4[use_aes]
    assert looks_encrypted(wire) is (PONG_SEALED_U16_AT_4[use_aes] > CIPHERTEXT_TYPE_THRESHOLD)
    assert rx.open(wire) == pdu
    assert rx.rx_seq == 2
    # the plaintext really starts with the sequence number
    assert rx._open_raw(wire)[:4] == (2).to_bytes(4, "little")


@pytest.mark.parametrize("use_aes", [False, True])
def test_replay_and_stale_frames_are_dropped_unless_permissive(use_aes):
    tx = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=use_aes)
    strict = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=use_aes)
    permissive = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=use_aes, replay_check=False)
    first = tx.seal(b"A")
    second = tx.seal(b"B")
    assert strict.open(second) == b"B"
    assert strict.open(first) is None           # stale: rx (3) >= seq (2)
    assert strict.open(second) is None          # replay
    assert strict.rx_seq == 3
    # the Kotlin phone stores whatever sequence arrives
    assert permissive.open(second) == b"B"
    assert permissive.open(first) == b"A"
    assert permissive.rx_seq == 2


def test_cross_aead_and_wrong_key_fail_authentication_without_advancing():
    aes = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=True)
    chacha = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L), use_aes=False)
    wire = aes.seal(b"payload")
    with pytest.raises(InvalidTag):
        chacha.open(wire)
    other_key = WifiSealer(SealedSession(b"K" * 32, SYNTHETIC_K, SYNTHETIC_L), use_aes=True)
    with pytest.raises(InvalidTag):
        other_key.open(wire)
    assert chacha.rx_seq == -1 and other_key.rx_seq == -1
    with pytest.raises(ValueError, match="at least 16 bytes"):
        aes.open(b"short")


def test_counters_can_be_shared_with_the_ble_session():
    """Non-881 models continue the BLE statics z.M/z.N on Wi-Fi."""
    ble = SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L)
    ble.seal(b"ble frame")           # M -> 2
    wifi = WifiSealer(ble)
    wifi.seal(b"wifi frame")         # M -> 3, on the same counter
    assert ble.tx_seq == 3 and wifi.tx_seq == 3
    peer = WifiSealer(SealedSession(SYNTHETIC_J, SYNTHETIC_K, SYNTHETIC_L))
    peer.counters.rx_seq = 2         # the peer already saw BLE seq 2
    assert peer.open(wifi.seal(b"x")) == b"x"   # seq 4 > 2
    assert PDU_HEADER_LEN == 8


def test_opt_int_treats_non_finite_numbers_as_absent():
    """Review T5: `{"start": 1e400}` parses to float inf and int(inf) raised
    OverflowError inside a request handler. HARNESS_POLICY: a non-finite
    number (or a numeric string that overflows) reads as the default, like a
    missing key -- Python has no Java-style narrowing to copy."""
    from plaudsim.wifi import FileSyncRequest, _opt_int

    assert _opt_int({"a": float("inf")}, "a", 7) == 7
    assert _opt_int({"a": float("-inf")}, "a", 7) == 7
    assert _opt_int({"a": float("nan")}, "a", 7) == 7
    assert _opt_int({"a": "1e400"}, "a", 7) == 7
    assert _opt_int({"a": "nan"}, "a", 7) == 7
    assert _opt_int({"a": 12.9}, "a", 7) == 12 and _opt_int({"a": "12.9"}, "a", 7) == 12
    req = FileSyncRequest.from_pdu(parse_pdu(pack_pdu(12, b'{"session":5,"scene":1,"start":1e400,"end":0}')))
    assert (req.session, req.start, req.end) == (5, 0, 0)
