"""R6-S2: independent Ogg/Opus validation of the R6-S1 contract.

SYNTHETIC FIXTURES -- NOT PLAUD CAPTURES. Generated by
scripts/generate_r6s2_fixture.py (PyAV/libopus, 16 kHz, 32 kbps CBR);
params + sha256 pinned in tests/fixtures/r6s2_manifest.json and
re-asserted here. Claims kept separate per the sprint: (A) generic
Ogg/Opus works, (B) the SDK Java-side contract is consistent with it,
(C) real Plaud bytes confirmed Ogg/Opus -- C REMAINS OPEN.

Requires PyAV + numpy (decoder/encoder side only; audio.py itself is
dependency-free). Opus is lossy: waveform similarity uses an explicit
correlation threshold, never bit-identity.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parents[1] / "reference/upstream/bumble"))
sys.path.insert(0, str(Path(__file__).parents[1] / "emulator"))
sys.path.insert(0, str(Path(__file__).parents[1] / "scripts"))

av = pytest.importorskip("av")
np = pytest.importorskip("numpy")

from plaudsim.audio import (  # noqa: E402
    classify_ogg_pages,
    h4_payload_spans,
    iter_ogg_pages,
    reassemble_page_packets,
)

import generate_r6s2_fixture as gen  # noqa: E402

FIX = Path(__file__).parent / "fixtures"
MANIFEST = json.loads((FIX / "r6s2_manifest.json").read_text())
BY_NAME = {f["path"]: f for f in MANIFEST["fixtures"]}

MONO = (FIX / "r6s2_16k_mono.ogg").read_bytes()
STEREO = (FIX / "r6s2_16k_stereo.ogg").read_bytes()

# Committed-fixture pins (regenerate + update deliberately, never silently).
EXPECTED = {
    "r6s2_16k_mono.ogg": {"pages": 5, "packets": 101, "channels": 1},
    "r6s2_16k_stereo.ogg": {"pages": 5, "packets": 101, "channels": 2},
}


def audio_packets(raw: bytes):
    pages = list(iter_ogg_pages(raw))
    roles = classify_ogg_pages(pages)
    packets = []
    for page in roles["audio_pages"]:
        packets += reassemble_page_packets(page["lacing"], page["payload"])
    return pages, roles, packets


def demux_audio_packets(raw: bytes, name: str):
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=True) as tmp:
        tmp.write(raw)
        tmp.flush()
        container = av.open(tmp.name)
        return [bytes(p) for p in container.demux(container.streams.audio[0])]


# --- fixture identity (§11) ----------------------------------------------------


def test_manifest_pins_synthetic_labeled_fixtures() -> None:
    for name, pins in EXPECTED.items():
        meta = BY_NAME[name]
        assert meta["synthetic"] is True and meta["not_plaud_capture"] is True
        assert meta["sample_rate"] == 16000 and meta["channels"] == pins["channels"]
        assert meta["bit_rate"] == 32000
        actual = hashlib.sha256((FIX / name).read_bytes()).hexdigest()
        assert actual == meta["sha256"], f"{name} drifted from manifest"


def test_ogg_structure_page_and_packet_counts() -> None:
    for name, pins in EXPECTED.items():
        raw = (FIX / name).read_bytes()
        pages, roles, packets = audio_packets(raw)
        assert len(pages) == pins["pages"]
        assert roles["head"]["channels"] == pins["channels"]
        assert roles["head"]["sample_rate"] == 16000
        assert roles["tags_dropped"] is True
        assert len(packets) == pins["packets"]
        assert all(len(p) > 0 for p in packets)


# --- R6 parser vs independent demuxer (§4) -------------------------------------


def test_r6_packets_match_independent_demux() -> None:
    # audio.py extraction is byte-identical to PyAV's own Ogg demuxer output
    # (modulo its zero-length trailing flush packet), ordered.
    _, _, packets = audio_packets(MONO)
    demuxed = demux_audio_packets(MONO, "mono")
    assert len(demuxed) == len(packets) + 1
    assert demuxed[-1] == b""  # encoder-drain flush, documented
    assert demuxed[:-1] == packets


def test_packet_lengths_are_genuine_vbr_not_80b() -> None:
    # Honest structural note: a standard encoder emits variable lengths;
    # Plaud's fixed-80 CBR framing is a device-side property, not Ogg's.
    _, _, packets = audio_packets(MONO)
    assert len(set(map(len, packets))) > 5
    assert set(map(len, packets)) != {80}


# --- independent decode of R6-extracted packets (§5) ---------------------------


def test_extracted_packets_decode_independently() -> None:
    # Claim: R6-extracted packets are valid Opus accepted by an independent
    # decoder with the expected frame structure (NOT a claim about native
    # OpusUtils internals).
    from av import CodecContext, Packet

    _, _, packets = audio_packets(MONO)
    decoder = CodecContext.create("opus", "r")
    for raw in (packets[0], packets[len(packets) // 2], packets[-1]):
        frames = decoder.decode(Packet(raw))
        assert len(frames) == 1
        assert frames[0].samples == 960  # 20 ms @ 48 kHz
        assert frames[0].sample_rate == 48000


def decode_fixture(raw: bytes):
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=True) as tmp:
        tmp.write(raw)
        tmp.flush()
        container = av.open(tmp.name)
        stream = container.streams.audio[0]
        return stream, [f for f in container.decode(stream)]


def test_full_decode_pcm_properties_and_similarity() -> None:
    stream, frames = decode_fixture(MONO)
    decoded = np.concatenate([f.to_ndarray() for f in frames], axis=1)
    assert decoded.shape == (1, 96000)  # 2.0 s @ 48 kHz mono
    assert frames[0].sample_rate == 48000
    source = gen.pcm_source(1).reshape(-1).astype(np.float64)
    heard = decoded[0].astype(np.float64)[::3][: 16000 * 2]
    a, b = heard[500:-500], source[500:-500]
    corr = float(np.dot(a, b) / np.sqrt(np.dot(a, a) * np.dot(b, b)))
    assert corr > 0.90, f"decoded/source correlation {corr}"  # lossy: threshold, not identity


def test_stereo_decode_shape() -> None:
    stream, frames = decode_fixture(STEREO)
    decoded = np.concatenate([f.to_ndarray() for f in frames], axis=1)
    assert decoded.shape == (2, 96000)
    _, roles, packets = audio_packets(STEREO)
    assert roles["head"]["channels"] == 2 and len(packets) == 101


# --- Plaud framing hypothesis stays OPEN (§6) ----------------------------------


def test_standard_ogg_does_not_match_h4_wire_framing() -> None:
    # h4 spans (512 skip, 1536-byte frames) cut mid-page on standard Ogg:
    # the first span's bytes are NOT the first opus packet. This honest
    # mismatch is why claim C (real Plaud bytes == this layout) stays OPEN;
    # the 512-B header content itself is UNKNOWN, so no wrapper is built.
    spans = h4_payload_spans(len(MONO), 1)
    assert len(spans) >= 1
    off, _ = spans[0]
    assert MONO[off : off + 80] != audio_packets(MONO)[2][0][:80]


# --- negatives (§8; independent-decoder behavior only) -------------------------


def test_corrupt_ogg_fails_parser_side() -> None:
    # Bad magic: the walk stops with zero pages (no resync invented, no
    # exception escapes the generator by design -- mirrors the SDK's abort).
    assert list(iter_ogg_pages(b"XXXX" + MONO[4:100])) == []
    pages = list(iter_ogg_pages(MONO[: len(MONO) // 2]))
    assert len(pages) < 5  # truncation stops the walk; no resync invented


def test_malformed_opus_recorded_not_attributed() -> None:
    # Behavior of the INDEPENDENT decoder (PyAV/libopus). Not attributed to
    # Plaud's native decoder, whose invalid-input behavior is UNKNOWN.
    from av import CodecContext, Packet

    decoder = CodecContext.create("opus", "r")
    with pytest.raises(Exception):
        decoder.decode(Packet(bytes([0xFF]) * 80))
    assert decoder.decode(Packet(b"")) == []  # empty input: no frames, no error
