"""Software-only Plaud/Tinno protocol components.

Layering (do not collapse these):
    handshake.py  pre-handshake marker framing, secret-package split, the
                  post-handshake ChaCha envelope, l3/x2 response parsers
    filesync.py   pure codecs for the recording/file-sync message family
    transfer.py   device-side transfer + file-list state machines
    profile.py    the Bumble GATT peripheral that drives them
    wifi.py       pure codecs for the Wi-Fi WebSocket channel (ledger section 7)
    wifi_device.py the device side of that channel: an asyncio WebSocket CLIENT
"""

from .advertising import (
    PRODUCT_NAMES,
    ScanFields,
    build_manufacturer_data,
    parse_manufacturer_data,
)
from .filesync import (
    EMPTY_PACKAGE_OFFSET,
    FILE_DATA_TYPE,
    FILE_LIST_ENTRY_OFFSET,
    OPCODE_FILE_LIST,
    OPCODE_RATE_TEST,
    OPCODE_DELETE_FILE,
    OPCODE_DELETE_FILE_RSP,
    OPCODE_RESUME,
    OPCODE_STOP_SYNC,
    OPCODE_STOP_SYNC_RSP,
    OPCODE_SYNC_HEAD,
    OPCODE_SYNC_START,
    OPCODE_SYNC_TAIL,
    RATE_TEST_TYPE,
    file_entry_stride,
    pack_delete_file_request,
    pack_file_list_request,
    pack_resume_record_request,
    pack_stop_sync_request,
    pack_sync_start,
    parse_file_data_frame,
    parse_file_entry,
    parse_file_list_frame,
    parse_delete_file_response,
    parse_rate_test_frame,
    parse_resume_record_response,
    parse_stop_sync_response,
    parse_sync_head,
    parse_sync_tail,
)
from .handshake import (
    build_k3,
    build_k3_from_historical_id,
    normalize_historical_id,
    CHUNK_SIZE,
    MARKER_FORCE_CLEAR,
    MARKER_PRE_HANDSHAKE,
    MARKER_RSA_MARKER,
    MARKER_SECRET,
    MARKERS,
    SECRET_MAGIC,
    SECRET_MIN_LEN,
    ReplayWindow,
    chunk_bytes,
    encode_l3,
    encode_x2,
    pack_marker_frame,
    parse_handshake_request,
    parse_l3,
    parse_marker_frame,
    parse_x2,
    reassemble_secret_chunks,
    select_handshake_response,
    split_secret_package,
    unwrap_envelope_plaintext,
    wrap_envelope_plaintext,
)
from .profile import (
    ENCRYPTED_PORT_VERSION,
    GET_STATE_REQUEST,
    GET_STORAGE_REQUEST,
    PORT_VERSION,
    PlaudBatteryState,
    PlaudDeviceState,
    PlaudLifecycle,
    PlaudPeripheral,
    PlaudR1aPeripheral,
    PlaudStorageState,
    PlaudSyncTimeState,
    COMMON_ACTION_READ,
    COMMON_ACTION_SET,
    COMMON_TYPE_NAMES,
    OPCODE_COMMON_SETTINGS,
    encode_common_settings_response,
    encode_feature_frame,
    parse_common_settings_request,
    parse_feature_request,
    parse_sync_time_request,
    DEFAULT_WEBSOCKET_PROFILE,
    OPCODE_CLOSE_WIFI,
    OPCODE_OPEN_WIFI,
    OPCODE_WEBSOCKET_REQ,
    OPCODE_WEBSOCKET_RSP,
    WEBSOCKET_OP_GET,
    WEBSOCKET_OP_SET,
    WEBSOCKET_TYPE_DEV_TOKEN,
    WEBSOCKET_TYPE_NAMES,
    WEBSOCKET_TYPE_SER_TOKEN,
    WEBSOCKET_TYPE_URL,
    WEBSOCKET_VALUE_WIDTH,
    WIFI_OPEN_STATUS_BUSY,
    WIFI_PASS_LEN,
    encode_close_wifi_response,
    encode_open_wifi_response,
    encode_websocket_get_request,
    encode_websocket_response,
    encode_websocket_set_request,
    parse_close_wifi_request,
    parse_close_wifi_response,
    parse_open_wifi_request,
    parse_open_wifi_response,
    parse_websocket_request,
    parse_websocket_response,
)
from .wifi import (
    CIPHERTEXT_TYPE_THRESHOLD,
    MESSAGE_NAMES,
    PDU_HEADER_LEN,
    PDU_VERSION_HOST,
    WS_PORT,
    FileRecord,
    Pdu,
    WifiSealer,
    looks_encrypted,
    pack_file_records,
    pack_pdu,
    pad_wifi_token,
    parse_file_records,
    parse_pdu,
)
from .wifi_device import (
    WifiDevice,
    WifiDeviceState,
    WifiFileStore,
    WifiStatusPolicy,
)
from .transfer import (
    DEFAULT_EMPTY_PACKAGE_CODE,
    FileListAccumulator,
    FileTable,
    TransferSession,
    pack_empty_package_frame,
    pack_file_data_frame,
    pack_file_list_frame,
    pack_resume_record_response,
    pack_sync_head,
    pack_sync_tail,
    parse_file_list_request,
    parse_resume_record_request,
    parse_sync_start_request,
)

__all__ = [n for n in dir() if not n.startswith("_")]
